name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, local-machine]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to docker Hub
        run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: sudo docker build --platform linux/amd64 -t parth404/upsplit_server:1.0 .
      - name: Publish Image to docker hub
        run: sudo docker push parth404/upsplit_server:1.0

  deploy:
    needs: build
    runs-on: [ip-172-31-43-61]
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull parth404/upsplit_server:1.0
      - name: Delete Old Container
        run: sudo docker rm -f upsplit-container
      - name: Run DockerContainer
        run: sudo docker run -p 8000:8000 -name upsplit-container parth404/upsplit:1.0
