name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t parth404/upsplit_server:1.0 .
      - name: Publish Image to Docker Hub
        run: docker push parth404/upsplit_server:1.0

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull parth404/upsplit_server:1.0
      - name: Delete Old Container
        run: docker rm -f upsplit-container || true
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name upsplit-container parth404/upsplit_server:1.0
