name: CICD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull parth404/upsplit_server:latest
      - name: Delete Old Container
        run: sudo docker rm -f upsplit-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name upsplit-container parth404/upsplit_server:latest
